Добавляет фронтпэйдж
htmlacademy-htmlcss/1905633-sedona-32 pull request #2
Opened 2021-10-02 10:55 UTC by Rybus1

Первая черновая вёрстка лицевой страницы

2021-10-12 21:03 UTC, Viktor-Rybakov commented on index.html
> +          <img src="" alt="Sedona-photo-2">
Получается в каждом элементе списка будет заголовок и описание. В двух элементах будет картинка (их расположение слева или справа потом определим в стилях), и в первом элементе (прям внутри) вложен еще один список из трех элементов

2021-10-12 21:07 UTC, Viktor-Rybakov commented on index.html
> +      <span class="footer-phone">
Этот `span` не нужен, тега `a` достаточно, чтобы оформить и спозиционировать текст.

2021-10-12 21:09 UTC, Viktor-Rybakov commented on index.html
> +          <img src="" alt="academy-logo">
Здесь нужна не картинка, а скрытый текст. В таком случае, как сделано сейчас, картинка тоже не будет видна, потому что она обернута в тег с классом visually-hidden, который визуально скрывает элемент.

2021-10-12 21:09 UTC, Viktor-Rybakov commented on index.html
> +<!---<p>Репозиторий создан для обучения на профессиональном онлайн‑курсе «<a href="https://htmlacademy.ru/intensive/htmlcss">HTML и CSS. Профессиональная вёрстка сайтов</a>».</p>-->
Это можно вообще удалить.

2021-10-12 21:10 UTC, Viktor-Rybakov commented on index.html
> +      <p>
У элементов списка можно сделать заголовки, получатся h2 и h3

2021-10-12 21:11 UTC, Viktor-Rybakov commented on catalog.html
> +          <a href="#" class="navigation-link">Главная</a>
Эта ссылка ведет на главную страницу, index.html

2021-10-12 21:13 UTC, Viktor-Rybakov commented on catalog.html
> +            <img src="" alt="home-page-logo">
Иконку домика вставим в стилях, а внутри ссылки должен быть скрытый текст "Домой", чтобы было понятно, куда эта ссылка ведет

2021-10-12 21:17 UTC, Viktor-Rybakov commented on catalog.html
> +        <button class="button">Сбросить</button>
Чтобы сбросить форму, у кнопки нужен атрибут `type="reset"`

2021-10-12 21:21 UTC, Viktor-Rybakov commented on index.html
> +    <section class="footer-credentials">
Если добавляешь тут секцию, то для секции нужно добавить скрытый заголовок

2021-10-12 21:30 UTC, Viktor-Rybakov commented on catalog.html
> +            </li>
Не закрыт тег `ul`

2021-10-12 21:34 UTC, Viktor-Rybakov commented on catalog.html
> +    </section>
В секции допускается располагать `header` и `footer`. В этом месте в хедер можно расположить заголовок секции, сортировку и кнопки отображения.
А в футер поместить пагинатор.

Тогда основным контентом в секции будет список гостиниц.

Как сделано сейчас - не совсем правильно, что в секции выделены загловок с сортировкой и пагинатор.

2021-11-10 22:00 UTC, Viktor-Rybakov requested changes
Страница каталога не проходит валидацию: https://validator.w3.org/nu/#textarea

Вы используете много дробных размеров в пикселях - округлите их до целого.

Нужно использовать один способ записи цветов - у вас и хексы (#) и ключевые слова

В названиях svg файлов есть знак `=`, лучше не использовать его в названиях файлов.
Для оптимизации файлов svg используйте спец. сервис [SVGOMG](https://jakearchibald.github.io/svgomg/) - можно и нужно для оптимизации уменьшить точность отрисовки (достаточно двух цифр после зяпятой) - так файл будет занимать много меньше места.

2021-11-10 22:00 UTC, Viktor-Rybakov commented on index.html
> +    <section class="advantages-section">
Для секции нужно добавить заголовок h2 и скрыть его
![изображение](https://user-images.githubusercontent.com/53224541/141193425-b490b58c-2490-4784-8332-2061d071db7e.png)

2021-11-10 22:00 UTC, Viktor-Rybakov commented on index.html
> +              <div class="house-icon"></div>
Эти иконки не нужно встявлять в разметку, их добавим в css фоном для `advantage-navyblue-pile` и таких же других

2021-11-10 22:00 UTC, Viktor-Rybakov commented on catalog.html
> +          <div class="arrow-icon"></div>
Эту иконку не нужно вставлять в разметку, её добавим в стилях с помощью псевдоэлемента

2021-11-10 22:00 UTC, Viktor-Rybakov commented on catalog.html
> +          <span class="search-number-found"></span>
здесь, похоже, подразумевается количество гостиниц?

2021-11-10 22:00 UTC, Viktor-Rybakov commented on catalog.html
> +          </a>
Кнопка начинается тегом `button`, а заканчивается тегом `a`

2021-11-10 22:00 UTC, Viktor-Rybakov commented on catalog.html
> +        <select name="pagination-results-list">
Здесь нужно сделать такую же конструкцию с формой как в `sorting-type`

2021-11-10 22:00 UTC, Viktor-Rybakov commented on catalog.html
> +    <section class="footer-credentials">
Нет заголовка у секции

2021-11-10 22:00 UTC, Viktor-Rybakov commented on styles/styles.css
> +button {
Вы добавляете стили для всех кнопок в проекте (глобальный селектор), что является плохой практикой, и запрещено  [критериями](https://up.htmlacademy.ru/htmlcss/32/criteries#CSS-02)

И то же замечание к остальным глобальным селекторам.

2021-11-10 22:00 UTC, Viktor-Rybakov commented on styles/styles.css
> +    line-height: 25,88px;
В таком случае лучше округлить до целого значения. Бывает, что браузер размыто отображает дробные пиксели

2021-11-10 22:00 UTC, Viktor-Rybakov commented on styles/styles.css
> +    color: black;
Посмотрите [критерий со код гайдом](https://up.htmlacademy.ru/htmlcss/32/criteries#PROJ-01)

`Цвет в разных блоках используется в одинаковой нотации.`

2021-11-10 22:00 UTC, Viktor-Rybakov commented on styles/styles.css
> +    background-color: white;
Дублирование строки 21

2021-11-10 22:00 UTC, Viktor-Rybakov commented on styles/styles.css
> +.advantage-header {
Добавить размер шрифта и высоту строки

2021-11-10 22:00 UTC, Viktor-Rybakov commented on index.html
> +          <p class="advantage-description">
Добавить в стилях цвет

2021-11-10 22:00 UTC, Viktor-Rybakov commented on styles/styles.css
> +.black-header {
Задать размер шрифта и высоту строки, они не наследуются от секции

2021-11-13 18:37 UTC, Rybus1 commented on index.html
> +      <!--Зубчастая втулка
Комментарий и этот кусок кода убрал.

2021-11-13 18:41 UTC, Rybus1 commented on index.html
> +    <section class="advantages-section">
Добавил H2 "Список преимуществ Седоны"

2021-11-13 18:43 UTC, Rybus1 commented on index.html
> +              <div class="house-icon"></div>
Дивы убрал, добавил класс иконок в li

2021-11-13 18:45 UTC, Rybus1 commented on catalog.html
> +          <div class="arrow-icon"></div>
Убрал из каталога и CSS'а

2021-11-13 18:46 UTC, Rybus1 commented on catalog.html
> +          <span class="search-number-found"></span>
Да, я думал что возможно это число ("38") должно приходить откуда-то с бэкенда
Но пока что просто убрал спан.

2021-11-13 18:47 UTC, Rybus1 commented on catalog.html
> +          </a>
Поправил и выровнял

2021-11-13 18:53 UTC, Rybus1 commented on catalog.html
> +        <select name="pagination-results-list">
Этот момент надо будет обсудить, но вроде бы сделал

2021-11-13 18:54 UTC, Rybus1 commented on catalog.html
> +    <section class="footer-credentials">
Добавил

2021-11-13 19:12 UTC, Rybus1 commented on styles/styles.css
> +button {
Убрал стили для глобального button, сделал отдельный классы brown-button и blue-button.
Так же поправил для списков, редеров и ссылок.

2021-11-13 19:12 UTC, Rybus1 commented on styles/styles.css
> +    line-height: 25,88px;
Все дробные заменил на целые

2021-11-13 19:13 UTC, Rybus1 commented on styles/styles.css
> +    color: black;
Везде заменил на хексы

2021-11-13 19:15 UTC, Rybus1 commented on styles/styles.css
> +    background-color: white;
Дублированную строку убрал.
Color: #333333 - это разве не цвет текста по умолчанию?

2021-11-13 19:17 UTC, Rybus1 commented on styles/styles.css
> +.general-section-reasons {
Высоту строки добавил.
Цвет тоже сделал. Хотя мне казалось, что тут можно просто унаследовать из body.

2021-11-13 19:18 UTC, Rybus1 commented on styles/styles.css
> +.advantage-blue-pile {
Шикарный совет. Возьму на заметку. Сильно упростит жизнь.

2021-11-13 19:19 UTC, Rybus1 commented on styles/styles.css
> +.advantage-header {
Добавил

2021-11-13 19:22 UTC, Rybus1 commented on index.html
> +          <p class="advantage-description">
Добавил.
Опять же, не прописывал его потому что он такой же, как в общем правиле в body.

2021-11-13 19:23 UTC, Rybus1 commented on styles/styles.css
> +.invitation-description {
Добавлено

2021-11-13 19:26 UTC, Rybus1 commented on styles/styles.css
> +.black-header {
Сделал

2021-11-13 19:39 UTC, Rybus1 commented on styles/styles.css
> +.visually-hidden {
Прочитал, но мне необходим пример, что бы понять эту разницу и что правильнее применять в нашем случае.

2021-11-13 19:40 UTC, Rybus1 commented on styles/styles.css
> +fieldset {
Исправлено

2021-11-14 15:12 UTC, Viktor-Rybakov approved these changes

2021-11-14 15:12 UTC, Viktor-Rybakov commented on catalog.html
> +        <button class="tile-look" href="#">
У кнопки нет атрибута href, но нужно добавить атрибут type

2021-11-14 15:12 UTC, Viktor-Rybakov commented
Нужно поправить замечание с кнопками, остальное всё хорошо!

2021-11-14 15:12 UTC, merged