Расставляет объекты по сеткам
htmlacademy-htmlcss/1905633-sedona-32 pull request #3
Opened 2021-11-17 03:42 UTC by Rybus1

Первая попытка создания сеток

2021-11-17 18:19 UTC, Viktor-Rybakov requested changes
Не до конца доделана сетка на странице каталога
![изображение](https://user-images.githubusercontent.com/53224541/142259086-bb2a7ce1-251e-40f0-8b69-e4c6132b640b.png)

2021-11-17 18:19 UTC, Viktor-Rybakov commented on index.html
> +              <li class="advantage-navyblue-pile house-icon pile">
![изображение](https://user-images.githubusercontent.com/53224541/142257191-13aa854c-8de2-4dca-b08d-0c5444b07374.png)
Для иконок нужно задать размер бекграунда: background-size, так ты переопределяешь размер самого блока

2021-11-17 18:19 UTC, Viktor-Rybakov commented on styles/styles.css
> +.price-range {
К сожалению, для fieldset не работает грид. решается с помощью добавления внутрь дополнительного дива, для которого уже описывается display: grid. Это такой баг
https://stackoverflow.com/questions/51076747/grid-layout-on-fieldset-bug-on-chrome

2021-11-17 18:19 UTC, Viktor-Rybakov commented on styles/styles.css
> +.price-range {
К сожалению, для fieldset не работает грид. решается с помощью добавления внутрь дополнительного дива, для которого уже описывается display: grid. Это такой баг
https://stackoverflow.com/questions/51076747/grid-layout-on-fieldset-bug-on-chrome

2021-11-18 00:17 UTC, Rybus1 commented on index.html
> +        <ul class="advantages-list main-pile-list list">
Исправил, но пришлось сделать обёртку вокруг текстовых элементов, что бы они не были детьми одного уровня с картинкой. Иначе всё выкладывалось по горизонтали.

2021-11-18 00:21 UTC, Rybus1 commented on index.html
> +              <li class="advantage-navyblue-pile house-icon pile">
Не знал, исправил.

2021-11-18 00:23 UTC, Rybus1 commented on styles/styles.css
> +.price-range {
А почему не работает? У меня же вроде всё выстроилось в правильном порядке.

2021-11-18 11:17 UTC, Viktor-Rybakov commented on index.html
> +        <ul class="advantages-list main-pile-list list">
Да, так и нужно!

2021-11-18 21:44 UTC, Viktor-Rybakov requested changes
**Важно!** - у вас в секциях задается высота. Так делать нельзя потому, что в какой-то момент может поменяться контент на странице (станет больше текста) и он не поместится. Прочитайте [статью про переполнение](https://up.htmlacademy.ru/htmlcss/32/book/8.2.7)

В верней секции съехали фоновые картинки
![изображение](https://user-images.githubusercontent.com/53224541/142495610-2f826e15-ae35-49bd-a2dc-94c25385bc60.png)

Контейнер `background-border` излишний, фоновую картинку (`main-page-border.svg`) можно задать и спозиционировать секции `general-section`.
Можно задавать несколько фоновых рисунков через запятую https://doka.guide/css/background-image/

Правый марджин должен располагаться там же, где вы делаете отступ слева. Такие отступы логично и правильно задавать в одном месте - в вашем случае это класс `inner-header` - задать паддинг слева и справа
![изображение](https://user-images.githubusercontent.com/53224541/142498443-d0c9b7fd-e900-4985-8d6a-497ff13f9dac.png)
![изображение](https://user-images.githubusercontent.com/53224541/142498520-707c2c50-fc5b-4cbf-a60f-98712c7f743b.png)

Очень странное задание марджина. Прочитайте учебник [3.8. Правила организации внешних отступов в вёрстке](https://up.htmlacademy.ru/htmlcss/32/book/3.8)
![изображение](https://user-images.githubusercontent.com/53224541/142499112-92afffbf-f1c7-43a5-9477-8a88c6810c85.png)

Про то же: задаете картинке внешние отступы паддингами. Внешние отступы нужно задавать марджинами и в этом случае - ссылке, в которую обернута картинка
![изображение](https://user-images.githubusercontent.com/53224541/142499653-4e78f599-7bbc-40a0-861e-9c311911c2e7.png)

Опять про отступы - верхний отступ нужно задавать не кнопке
![изображение](https://user-images.githubusercontent.com/53224541/142499993-0a67aa02-ce17-40ee-81ea-0d201a69a7a8.png)

То же - отступ должен быть у списка
![изображение](https://user-images.githubusercontent.com/53224541/142500055-9bd70cef-dffe-4b73-a6a6-df98ec28dda9.png)

А тут у формы
![изображение](https://user-images.githubusercontent.com/53224541/142500151-c2208078-4e13-4b94-9c84-d6c675e7e1d9.png)

2021-11-18 21:44 UTC, Viktor-Rybakov commented on index.html
>          <span class="visually-hidden">
Класс `visually-hidden` нужно поставить прямо для тега `h2`, оборачивать в `span` не нужно

2021-11-18 21:44 UTC, Viktor-Rybakov commented on index.html
> +            <ul class="list light-row-container">
Этот список "Жильё - Еда - Сувениры" не является отдельным элементом `li` списка `<ul class="advantages-list main-pile-list list">`, он входит внутрь **первого** элемента

В первом элементе будет примерно такая разметка:

```
<li class="advantage-blue-pile wide-pile">
<div>...</div>
<img>
<ul class="list light-row-container">...</ul>
</li>
```

2021-11-18 21:44 UTC, Viktor-Rybakov commented on index.html
> +              <li class="advantage-white-pile burger-icon pile">
Поправить позиционирование иконок
![изображение](https://user-images.githubusercontent.com/53224541/142497709-b57419ff-f2ed-4c06-967e-196a6c1381e4.png)

2021-11-18 21:44 UTC, Viktor-Rybakov commented on catalog.html
>        <div class="catalog-subscription">
Этот контейнер избыточен. Чтобы переопределить некоторые стили у секции `subscription`, добавьте этой секции **дополнительный** класс, например, `subscription-catalog`, в котором вы опишите все отличающиеся стили

2021-11-21 19:30 UTC, Rybus1 commented on index.html
>          <span class="visually-hidden">
Поправил. Так же поправил все отступы (поназначал их контейнерам, а не мелким элементам).
У меня всё ещё проблемы с расположением двоих бекграунд картинок (вот те белый зубцы внизу главного бэкграунда). Я не понимаю как задавать позицию конкретно одной картинке из списка бэкграундовых картинок.
Нужна помощь,

2021-11-21 19:46 UTC, Rybus1 commented on index.html
> +            <ul class="list light-row-container">
Исправил.

2021-11-21 19:58 UTC, Rybus1 commented on index.html
>          <span class="visually-hidden">
Отбой, всё таки удалось поставить. Но это очень неудобно.

2021-11-21 19:58 UTC, Rybus1 commented on index.html
> +              <li class="advantage-white-pile burger-icon pile">
Поправил,

2021-11-21 20:07 UTC, Rybus1 commented on catalog.html
>        <div class="catalog-subscription">
Поправил

2021-11-22 19:45 UTC, merged